name: scars-3060ti
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.3.1
  - torchvision=0.18.1
  - pytorch-cuda=12.1
  - numpy=1.26.4
  - scipy=1.11.4
  - scikit-learn=1.4.2
  - pyyaml=6.0.2
  - h5py=3.11.0
  - pillow=10.4.0
  - matplotlib=3.8.4
  - xgboost=2.1.1
  - psutil=6.0.0
  - pytest=8.3.2
  - pip
  - pip:
      - -e . --no-deps
